package models

import (
	"context"
	"database/sql"
	"encoding/json"
	"log/slog"
	"strconv"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"
)

// InsightType defines the type of insight
type InsightType string

const (
	InsightTypeTransaction    InsightType = "transaction"    // Insight about a specific transaction
	InsightTypeSpendingAlert  InsightType = "spending_alert" // Alert about spending patterns
	InsightTypeTrend          InsightType = "trend"          // Trend observation
	InsightTypeRecommendation InsightType = "recommendation" // Actionable recommendation
	InsightTypeAnomaly        InsightType = "anomaly"        // Unusual activity detected
	InsightTypeSummary        InsightType = "summary"        // Period summary insight
)

// InsightMetadata holds structured data for an insight
type InsightMetadata struct {
	AmountCents   int64     `json:"amount_cents,omitempty"`
	CategoryName  string    `json:"category_name,omitempty"`
	EntityID      uuid.UUID `json:"entity_id,omitempty"`
	EntityName    string    `json:"entity_name,omitempty"`
	PercentChange float64   `json:"percent_change,omitempty"`
	ComparedTo    string    `json:"compared_to,omitempty"` // e.g., "last_month", "average"
	RelatedTxnIDs []string  `json:"related_txn_ids,omitempty"`
}

// Insight represents a financial insight generated by LLM analysis
type Insight struct {
	ID            uuid.UUID  `json:"id"`
	LedgerID      uuid.UUID  `json:"ledger_id"`
	TransactionID *uuid.UUID `json:"transaction_id,omitempty"` // NULL for general insights
	ReportID      *uuid.UUID `json:"report_id,omitempty"`      // Link to source report

	InsightType InsightType `json:"insight_type"`
	Content     string      `json:"content"`
	Importance  int         `json:"importance"` // 1-10 scale
	IsKey       bool        `json:"is_key"`     // Surface to dashboard
	IsDismissed bool        `json:"is_dismissed"`

	Metadata *InsightMetadata `json:"metadata,omitempty"`

	// Generation metadata
	LLMProvider string `json:"llm_provider,omitempty"`
	LLMModel    string `json:"llm_model,omitempty"`

	CreatedAt time.Time `json:"created_at"`
}

type InsightStore struct {
	pool *pgxpool.Pool
}

func NewInsightStore(pool *pgxpool.Pool) *InsightStore {
	return &InsightStore{pool: pool}
}

func (s *InsightStore) Create(ctx context.Context, i *Insight) error {
	if i.ID == uuid.Nil {
		i.ID = uuid.New()
	}
	i.CreatedAt = time.Now()

	if i.Importance < 1 {
		i.Importance = 1
	}
	if i.Importance > 10 {
		i.Importance = 10
	}

	var metadataJSON []byte
	if i.Metadata != nil {
		if b, jsonErr := json.Marshal(i.Metadata); jsonErr != nil {
			slog.WarnContext(ctx, "failed to marshal insight metadata", "insight_id", i.ID, "err", jsonErr)
		} else {
			metadataJSON = b
		}
	}

	_, err := s.pool.Exec(ctx, `
		INSERT INTO insights (
			id, ledger_id, transaction_id, report_id,
			insight_type, content, importance, is_key, is_dismissed,
			metadata, llm_provider, llm_model, created_at
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
	`, i.ID, i.LedgerID, i.TransactionID, i.ReportID,
		i.InsightType, i.Content, i.Importance, i.IsKey, i.IsDismissed,
		metadataJSON, NullString(i.LLMProvider), NullString(i.LLMModel), i.CreatedAt)

	return err
}

func (s *InsightStore) GetByID(ctx context.Context, id uuid.UUID) (*Insight, error) {
	i := &Insight{}
	var metadataJSON []byte
	var llmProvider, llmModel sql.NullString

	err := s.pool.QueryRow(ctx, `
		SELECT id, ledger_id, transaction_id, report_id,
			insight_type, content, importance, is_key, is_dismissed,
			metadata, llm_provider, llm_model, created_at
		FROM insights WHERE id = $1
	`, id).Scan(
		&i.ID, &i.LedgerID, &i.TransactionID, &i.ReportID,
		&i.InsightType, &i.Content, &i.Importance, &i.IsKey, &i.IsDismissed,
		&metadataJSON, &llmProvider, &llmModel, &i.CreatedAt)

	if err != nil {
		return nil, err
	}

	i.LLMProvider = llmProvider.String
	i.LLMModel = llmModel.String

	if len(metadataJSON) > 0 {
		i.Metadata = &InsightMetadata{}
		if err := json.Unmarshal(metadataJSON, i.Metadata); err != nil {
			slog.WarnContext(ctx, "failed to unmarshal insight metadata", "insight_id", i.ID, "err", err)
		}
	}

	return i, nil
}

// GetKeyInsights retrieves important, non-dismissed insights for a ledger
func (s *InsightStore) GetKeyInsights(ctx context.Context, ledgerID uuid.UUID, limit int) ([]*Insight, error) {
	if limit <= 0 {
		limit = 10
	}

	rows, err := s.pool.Query(ctx, `
		SELECT id, ledger_id, transaction_id, report_id,
			insight_type, content, importance, is_key, is_dismissed,
			metadata, llm_provider, llm_model, created_at
		FROM insights 
		WHERE ledger_id = $1 AND is_key = true AND is_dismissed = false
		ORDER BY importance DESC, created_at DESC
		LIMIT $2
	`, ledgerID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	return s.scanInsights(ctx, rows)
}

// GetRecentInsights retrieves recent non-dismissed insights for a ledger
func (s *InsightStore) GetRecentInsights(ctx context.Context, ledgerID uuid.UUID, limit int) ([]*Insight, error) {
	if limit <= 0 {
		limit = 20
	}

	rows, err := s.pool.Query(ctx, `
		SELECT id, ledger_id, transaction_id, report_id,
			insight_type, content, importance, is_key, is_dismissed,
			metadata, llm_provider, llm_model, created_at
		FROM insights 
		WHERE ledger_id = $1 AND is_dismissed = false
		ORDER BY created_at DESC
		LIMIT $2
	`, ledgerID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	return s.scanInsights(ctx, rows)
}

// GetByTransaction retrieves insights for a specific transaction
func (s *InsightStore) GetByTransaction(ctx context.Context, transactionID uuid.UUID) ([]*Insight, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT id, ledger_id, transaction_id, report_id,
			insight_type, content, importance, is_key, is_dismissed,
			metadata, llm_provider, llm_model, created_at
		FROM insights 
		WHERE transaction_id = $1
		ORDER BY created_at DESC
	`, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	return s.scanInsights(ctx, rows)
}

// GetByReport retrieves insights generated from a specific report
func (s *InsightStore) GetByReport(ctx context.Context, reportID uuid.UUID) ([]*Insight, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT id, ledger_id, transaction_id, report_id,
			insight_type, content, importance, is_key, is_dismissed,
			metadata, llm_provider, llm_model, created_at
		FROM insights 
		WHERE report_id = $1
		ORDER BY importance DESC, created_at DESC
	`, reportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	return s.scanInsights(ctx, rows)
}

// InsightFilter for querying insights
type InsightFilter struct {
	LedgerID         uuid.UUID
	InsightType      *InsightType
	MinImportance    *int
	IncludeDismissed bool
	KeyOnly          bool
	Since            *time.Time
	Limit            int
	Offset           int
}

// List retrieves insights with filtering
func (s *InsightStore) List(ctx context.Context, filter InsightFilter) ([]*Insight, int, error) {
	baseQuery := `FROM insights WHERE ledger_id = $1`
	args := []interface{}{filter.LedgerID}
	argIdx := 2

	if !filter.IncludeDismissed {
		baseQuery += ` AND is_dismissed = false`
	}

	if filter.KeyOnly {
		baseQuery += ` AND is_key = true`
	}

	if filter.InsightType != nil {
		baseQuery += ` AND insight_type = $` + strconv.Itoa(argIdx)
		args = append(args, *filter.InsightType)
		argIdx++
	}

	if filter.MinImportance != nil {
		baseQuery += ` AND importance >= $` + strconv.Itoa(argIdx)
		args = append(args, *filter.MinImportance)
		argIdx++
	}

	if filter.Since != nil {
		baseQuery += ` AND created_at >= $` + strconv.Itoa(argIdx)
		args = append(args, *filter.Since)
		argIdx++
	}

	// Count total
	var total int
	err := s.pool.QueryRow(ctx, `SELECT COUNT(*) `+baseQuery, args...).Scan(&total)
	if err != nil {
		return nil, 0, err
	}

	// Main query
	query := `SELECT id, ledger_id, transaction_id, report_id,
		insight_type, content, importance, is_key, is_dismissed,
		metadata, llm_provider, llm_model, created_at ` + baseQuery +
		` ORDER BY importance DESC, created_at DESC`

	if filter.Limit > 0 {
		query += ` LIMIT $` + strconv.Itoa(argIdx)
		args = append(args, filter.Limit)
		argIdx++
	}

	if filter.Offset > 0 {
		query += ` OFFSET $` + strconv.Itoa(argIdx)
		args = append(args, filter.Offset)
	}

	rows, err := s.pool.Query(ctx, query, args...)
	if err != nil {
		return nil, 0, err
	}
	defer rows.Close()

	insights, err := s.scanInsights(ctx, rows)
	return insights, total, err
}

// Dismiss marks an insight as dismissed
func (s *InsightStore) Dismiss(ctx context.Context, id uuid.UUID) error {
	_, err := s.pool.Exec(ctx, `
		UPDATE insights SET is_dismissed = true WHERE id = $1
	`, id)
	return err
}

// Delete removes an insight
func (s *InsightStore) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := s.pool.Exec(ctx, `DELETE FROM insights WHERE id = $1`, id)
	return err
}

// DeleteByReport deletes all insights for a report (for regeneration)
func (s *InsightStore) DeleteByReport(ctx context.Context, reportID uuid.UUID) error {
	_, err := s.pool.Exec(ctx, `DELETE FROM insights WHERE report_id = $1`, reportID)
	return err
}

// CleanupOld removes old dismissed insights (retention policy)
func (s *InsightStore) CleanupOld(ctx context.Context, olderThan time.Time) (int64, error) {
	result, err := s.pool.Exec(ctx, `
		DELETE FROM insights 
		WHERE is_dismissed = true AND created_at < $1
	`, olderThan)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

func (s *InsightStore) scanInsights(ctx context.Context, rows interface {
	Next() bool
	Scan(...interface{}) error
	Err() error
}) ([]*Insight, error) {
	var insights []*Insight
	for rows.Next() {
		i := &Insight{}
		var metadataJSON []byte
		var llmProvider, llmModel sql.NullString

		if err := rows.Scan(
			&i.ID, &i.LedgerID, &i.TransactionID, &i.ReportID,
			&i.InsightType, &i.Content, &i.Importance, &i.IsKey, &i.IsDismissed,
			&metadataJSON, &llmProvider, &llmModel, &i.CreatedAt,
		); err != nil {
			return nil, err
		}

		i.LLMProvider = llmProvider.String
		i.LLMModel = llmModel.String

		if len(metadataJSON) > 0 {
			i.Metadata = &InsightMetadata{}
			if err := json.Unmarshal(metadataJSON, i.Metadata); err != nil {
				slog.WarnContext(ctx, "failed to unmarshal insight metadata", "insight_id", i.ID, "err", err)
			}
		}

		insights = append(insights, i)
	}
	return insights, rows.Err()
}
