package models

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"log/slog"
	"strconv"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type Transaction struct {
	ID           uuid.UUID `json:"id"`
	LedgerID     uuid.UUID `json:"ledger_id"`
	Date         time.Time `json:"date"`
	Description  string    `json:"description"`
	DisplayTitle string    `json:"display_title,omitempty"` // Human-readable title generated by LLM
	Notes        string    `json:"notes,omitempty"`

	// Teller integration
	TellerTransactionID string `json:"teller_transaction_id,omitempty"`
	TellerType          string `json:"teller_type,omitempty"`           // e.g., "transfer", "ach", "wire", "card_payment"
	TellerCategory      string `json:"teller_category,omitempty"`       // Teller's pre-categorization: "groceries", "dining", etc.
	TellerStatus        string `json:"teller_status,omitempty"`         // "pending" or "posted"
	CounterpartyName    string `json:"counterparty_name,omitempty"`     // From Teller Details.Counterparty.Name
	CounterpartyType    string `json:"counterparty_type,omitempty"`     // "person" or "organization"
	RunningBalanceCents int64  `json:"running_balance_cents,omitempty"` // Balance after this transaction

	// Transfer tracking
	IsTransfer     bool         `json:"is_transfer"`
	TransferPairID *uuid.UUID   `json:"transfer_pair_id,omitempty"`
	TransferPair   *Transaction `json:"-"`                       // Loaded separately for display
	TransferType   string       `json:"transfer_type,omitempty"` // 'internal', 'household', 'person_payment', 'person_receipt', 'reimbursement'

	// Categorization queue status
	// pending, queued, processing, done, skipped, failed
	CategorizationStatus      string     `json:"categorization_status"`
	CategorizationError       string     `json:"categorization_error,omitempty"`
	CategorizationAttempts    int        `json:"categorization_attempts"`
	CategorizationQueuedAt    *time.Time `json:"categorization_queued_at,omitempty"`
	CategorizationCompletedAt *time.Time `json:"categorization_completed_at,omitempty"`

	// Enrichment
	RecurringPatternID *uuid.UUID `json:"recurring_pattern_id,omitempty"`
	EnrichmentStatus   string     `json:"enrichment_status,omitempty"` // pending, done, failed
	EnrichmentAttempts int        `json:"enrichment_attempts"`
	EnrichmentError    string     `json:"enrichment_error,omitempty"`
	EnrichedAt         *time.Time `json:"enriched_at,omitempty"`

	// Entity references
	EntityID             *uuid.UUID `json:"entity_id,omitempty"`              // The business/entity you transacted with
	CounterpartyEntityID *uuid.UUID `json:"counterparty_entity_id,omitempty"` // For transfers: the person/org on the other side
	IntermediaryEntityID *uuid.UUID `json:"intermediary_entity_id,omitempty"` // The financial intermediary (Zelle, ACH network, etc.)

	// Manual review tracking
	ReviewedAt *time.Time `json:"reviewed_at,omitempty"` // When user marked as reviewed (clears from needs_review)

	// Pattern detection
	PatternType              string                 `json:"pattern_type,omitempty"`             // salary, recurring_bill, account_transfer, investment_contribution, household_transfer, none
	PatternMetadata          map[string]interface{} `json:"pattern_metadata,omitempty"`         // Additional pattern-specific data
	PatternDetectionStatus   string                 `json:"pattern_detection_status,omitempty"` // pending, queued, processing, done, skipped, failed
	PatternDetectionAttempts int                    `json:"pattern_detection_attempts"`
	PatternDetectionError    string                 `json:"pattern_detection_error,omitempty"`

	// Vector embedding for semantic search
	Embedding          []float32  `json:"embedding,omitempty"`
	EmbeddingModel     string     `json:"embedding_model,omitempty"`
	EmbeddingUpdatedAt *time.Time `json:"embedding_updated_at,omitempty"`

	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	// Related data (loaded separately)
	Entries            []*Entry `json:"entries,omitempty"`
	Tags               []*Tag   `json:"tags,omitempty"`
	Entity             *Entity  `json:"entity,omitempty"`
	CounterpartyEntity *Entity  `json:"counterparty_entity,omitempty"`
	IntermediaryEntity *Entity  `json:"intermediary_entity,omitempty"`
}

type Entry struct {
	ID            uuid.UUID `json:"id"`
	TransactionID uuid.UUID `json:"transaction_id"`
	AccountID     uuid.UUID `json:"account_id"`
	AmountCents   int64     `json:"amount_cents"` // Positive = debit, Negative = credit
	Currency      string    `json:"currency"`
	CreatedAt     time.Time `json:"created_at"`

	// Loaded separately
	AccountName string      `json:"account_name,omitempty"`
	AccountType AccountType `json:"account_type,omitempty"`
}

type TransactionStore struct {
	pool *pgxpool.Pool
}

func NewTransactionStore(pool *pgxpool.Pool) *TransactionStore {
	return &TransactionStore{pool: pool}
}

// GetPool returns the database pool for creating other stores
func (s *TransactionStore) GetPool() *pgxpool.Pool {
	return s.pool
}

// CreateWithEntries creates a transaction with its entries in a single transaction
func (s *TransactionStore) CreateWithEntries(ctx context.Context, txn *Transaction, entries []*Entry) error {
	if txn.ID == uuid.Nil {
		txn.ID = uuid.New()
	}

	// Validate entries sum to zero
	var sum int64
	for _, e := range entries {
		sum += e.AmountCents
	}
	if sum != 0 {
		return ErrEntriesNotBalanced
	}

	// Default categorization status
	if txn.CategorizationStatus == "" {
		txn.CategorizationStatus = "pending"
	}
	// Default pattern detection status
	if txn.PatternDetectionStatus == "" {
		txn.PatternDetectionStatus = "pending"
	}

	return pgx.BeginFunc(ctx, s.pool, func(tx pgx.Tx) error {
		// Insert transaction
		var patternMetadataJSON []byte
		if txn.PatternMetadata != nil {
			var err error
			patternMetadataJSON, err = json.Marshal(txn.PatternMetadata)
			if err != nil {
				return fmt.Errorf("failed to marshal pattern metadata: %w", err)
			}
		}

		_, err := tx.Exec(ctx, `
			INSERT INTO transactions (id, ledger_id, date, description, notes,
				teller_transaction_id, teller_type, teller_category, teller_status,
				counterparty_name, counterparty_type, running_balance_cents,
				is_transfer, transfer_pair_id,
				categorization_status, categorization_queued_at,
				entity_id, counterparty_entity_id, intermediary_entity_id,
				pattern_type, pattern_metadata, pattern_detection_status,
				created_at, updated_at)
			VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24)
		`, txn.ID, txn.LedgerID, txn.Date, txn.Description, NullString(txn.Notes),
			NullString(txn.TellerTransactionID), NullString(txn.TellerType),
			NullString(txn.TellerCategory), NullString(txn.TellerStatus),
			NullString(txn.CounterpartyName), NullString(txn.CounterpartyType),
			NullInt64(txn.RunningBalanceCents),
			txn.IsTransfer, txn.TransferPairID,
			txn.CategorizationStatus, txn.CategorizationQueuedAt,
			txn.EntityID, txn.CounterpartyEntityID, txn.IntermediaryEntityID,
			NullString(txn.PatternType), patternMetadataJSON, txn.PatternDetectionStatus,
			time.Now(), time.Now())
		if err != nil {
			return err
		}

		// Insert entries
		for _, e := range entries {
			if e.ID == uuid.Nil {
				e.ID = uuid.New()
			}
			e.TransactionID = txn.ID

			_, err := tx.Exec(ctx, `
				INSERT INTO entries (id, transaction_id, account_id, amount_cents, currency, created_at)
				VALUES ($1, $2, $3, $4, $5, $6)
			`, e.ID, e.TransactionID, e.AccountID, e.AmountCents, e.Currency, time.Now())
			if err != nil {
				return err
			}
		}

		return nil
	})
}

func (s *TransactionStore) Update(ctx context.Context, txn *Transaction) error {
	_, err := s.pool.Exec(ctx, `
		UPDATE transactions SET
			date = $2, description = $3, display_title = $4, notes = $5,
			teller_type = $6, teller_category = $7, teller_status = $8,
			counterparty_name = $9, counterparty_type = $10, running_balance_cents = $11,
			is_transfer = $12, transfer_pair_id = $13,
			entity_id = $14, counterparty_entity_id = $15, intermediary_entity_id = $16,
			updated_at = $17
		WHERE id = $1
	`, txn.ID, txn.Date, txn.Description, NullString(txn.DisplayTitle), NullString(txn.Notes),
		NullString(txn.TellerType), NullString(txn.TellerCategory), NullString(txn.TellerStatus),
		NullString(txn.CounterpartyName), NullString(txn.CounterpartyType),
		NullInt64(txn.RunningBalanceCents),
		txn.IsTransfer, txn.TransferPairID,
		txn.EntityID, txn.CounterpartyEntityID, txn.IntermediaryEntityID,
		time.Now())

	return err
}

// UpdateWithEntries updates a transaction and replaces its entries
func (s *TransactionStore) UpdateWithEntries(ctx context.Context, txn *Transaction, entries []*Entry) error {
	// Validate entries sum to zero
	var sum int64
	for _, e := range entries {
		sum += e.AmountCents
	}
	if sum != 0 {
		return ErrEntriesNotBalanced
	}

	return pgx.BeginFunc(ctx, s.pool, func(tx pgx.Tx) error {
		// Update transaction
		_, err := tx.Exec(ctx, `
			UPDATE transactions SET
				date = $2, description = $3, display_title = $4, notes = $5,
				is_transfer = $6, updated_at = $7
			WHERE id = $1
		`, txn.ID, txn.Date, txn.Description, NullString(txn.DisplayTitle), NullString(txn.Notes),
			txn.IsTransfer, time.Now())
		if err != nil {
			return err
		}

		// Delete old entries
		_, err = tx.Exec(ctx, `DELETE FROM entries WHERE transaction_id = $1`, txn.ID)
		if err != nil {
			return err
		}

		// Insert new entries
		for _, e := range entries {
			if e.ID == uuid.Nil {
				e.ID = uuid.New()
			}
			e.TransactionID = txn.ID
			_, err = tx.Exec(ctx, `
				INSERT INTO entries (id, transaction_id, account_id, amount_cents, currency, created_at)
				VALUES ($1, $2, $3, $4, $5, $6)
			`, e.ID, e.TransactionID, e.AccountID, e.AmountCents, e.Currency, time.Now())
			if err != nil {
				return err
			}
		}

		return nil
	})
}

func (s *TransactionStore) Delete(ctx context.Context, id uuid.UUID) error {
	// Entries will cascade delete
	_, err := s.pool.Exec(ctx, `DELETE FROM transactions WHERE id = $1`, id)
	return err
}

// scanBasicTransaction scans the standard 20-column transaction row
// (id … updated_at, including display_title and entity IDs).
func scanBasicTransaction(s rowScanner) (*Transaction, error) {
	var t Transaction
	var displayTitle, notes, tellerTxnID, tellerType, tellerCategory, tellerStatus sql.NullString
	var counterpartyName, counterpartyType sql.NullString
	var runningBalanceCents sql.NullInt64
	var transferPairID *uuid.UUID

	if err := s.Scan(&t.ID, &t.LedgerID, &t.Date, &t.Description, &displayTitle, &notes,
		&tellerTxnID, &tellerType, &tellerCategory, &tellerStatus,
		&counterpartyName, &counterpartyType, &runningBalanceCents,
		&t.IsTransfer, &transferPairID,
		&t.EntityID, &t.CounterpartyEntityID, &t.IntermediaryEntityID,
		&t.CreatedAt, &t.UpdatedAt); err != nil {
		return nil, err
	}

	t.DisplayTitle = displayTitle.String
	applyNullTransactionFields(&t, notes, tellerTxnID, tellerType, tellerCategory, tellerStatus, counterpartyName, counterpartyType, runningBalanceCents)
	t.TransferPairID = transferPairID

	return &t, nil
}

// scanCoreTransactionRow scans the 16-column transaction row
// (id … updated_at, excluding display_title and entity IDs) used by
// unfiltered / un-joined transaction queries.
func scanCoreTransactionRow(rows pgx.Rows, t *Transaction) error {
	var notes, tellerTxnID, tellerType, tellerCategory, tellerStatus sql.NullString
	var counterpartyName, counterpartyType sql.NullString
	var runningBalanceCents sql.NullInt64
	if err := rows.Scan(
		&t.ID, &t.LedgerID, &t.Date, &t.Description, &notes,
		&tellerTxnID, &tellerType, &tellerCategory, &tellerStatus,
		&counterpartyName, &counterpartyType, &runningBalanceCents,
		&t.IsTransfer, &t.TransferPairID, &t.CreatedAt, &t.UpdatedAt,
	); err != nil {
		return err
	}
	applyNullTransactionFields(t, notes, tellerTxnID, tellerType, tellerCategory, tellerStatus, counterpartyName, counterpartyType, runningBalanceCents)
	return nil
}

// applyNullTransactionFields assigns the nullable provider and counterparty fields
// that appear in every transaction scan variant.
func applyNullTransactionFields(t *Transaction,
	notes, tellerTxnID, tellerType, tellerCategory, tellerStatus sql.NullString,
	counterpartyName, counterpartyType sql.NullString,
	runningBalanceCents sql.NullInt64) {
	t.Notes = notes.String
	t.TellerTransactionID = tellerTxnID.String
	t.TellerType = tellerType.String
	t.TellerCategory = tellerCategory.String
	t.TellerStatus = tellerStatus.String
	t.CounterpartyName = counterpartyName.String
	t.CounterpartyType = counterpartyType.String
	t.RunningBalanceCents = runningBalanceCents.Int64
}

func (s *TransactionStore) GetByID(ctx context.Context, id uuid.UUID) (*Transaction, error) {
	return scanBasicTransaction(s.pool.QueryRow(ctx, `
		SELECT id, ledger_id, date, description, display_title, notes,
			teller_transaction_id, teller_type, teller_category, teller_status,
			counterparty_name, counterparty_type, running_balance_cents,
			is_transfer, transfer_pair_id,
			entity_id, counterparty_entity_id, intermediary_entity_id,
			created_at, updated_at
		FROM transactions WHERE id = $1
	`, id))
}

// GetByEntityID returns ALL transactions for a specific entity within a ledger
// Used for entity-first pattern detection - we need full transaction history
func (s *TransactionStore) GetByEntityID(ctx context.Context, entityID, ledgerID uuid.UUID) ([]*Transaction, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT id, ledger_id, date, description, display_title, notes,
			teller_transaction_id, teller_type, teller_category, teller_status,
			counterparty_name, counterparty_type, running_balance_cents,
			is_transfer, transfer_pair_id,
			entity_id, counterparty_entity_id, intermediary_entity_id,
			created_at, updated_at
		FROM transactions 
		WHERE entity_id = $1 AND ledger_id = $2
		ORDER BY date ASC
	`, entityID, ledgerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var txns []*Transaction
	for rows.Next() {
		t, err := scanBasicTransaction(rows)
		if err != nil {
			return nil, err
		}
		txns = append(txns, t)
	}

	return txns, rows.Err()
}

func (s *TransactionStore) GetByTellerID(ctx context.Context, tellerID string) (*Transaction, error) {
	return scanBasicTransaction(s.pool.QueryRow(ctx, `
		SELECT id, ledger_id, date, description, display_title, notes,
			teller_transaction_id, teller_type, teller_category, teller_status,
			counterparty_name, counterparty_type, running_balance_cents,
			is_transfer, transfer_pair_id,
			entity_id, counterparty_entity_id, intermediary_entity_id,
			created_at, updated_at
		FROM transactions WHERE teller_transaction_id = $1
	`, tellerID))
}

type TransactionFilter struct {
	LedgerID   uuid.UUID
	AccountID  *uuid.UUID
	EntityID   *uuid.UUID
	StartDate  *time.Time
	EndDate    *time.Time
	TagID      *uuid.UUID
	IsTransfer *bool
	Search     string
	Limit      int
	Offset     int

	// Review filters
	Uncategorized bool     // Only transactions with no tags
	NeedsReview   bool     // Transactions with generic tags (General Merchandise, Other Income, etc.)
	TagNames      []string // Filter by specific tag names (for NeedsReview)
}

func (s *TransactionStore) List(ctx context.Context, filter TransactionFilter) ([]*Transaction, int, error) {
	baseQuery := `
		FROM transactions t
		WHERE t.ledger_id = $1
	`
	args := []any{filter.LedgerID}
	argIdx := 2

	if filter.AccountID != nil {
		baseQuery += ` AND EXISTS (SELECT 1 FROM entries e WHERE e.transaction_id = t.id AND e.account_id = $` + strconv.Itoa(argIdx) + `)`
		args = append(args, *filter.AccountID)
		argIdx++
	}

	if filter.EntityID != nil {
		baseQuery += ` AND t.entity_id = $` + strconv.Itoa(argIdx)
		args = append(args, *filter.EntityID)
		argIdx++
	}

	if filter.StartDate != nil {
		baseQuery += ` AND t.date >= $` + strconv.Itoa(argIdx)
		args = append(args, *filter.StartDate)
		argIdx++
	}

	if filter.EndDate != nil {
		baseQuery += ` AND t.date <= $` + strconv.Itoa(argIdx)
		args = append(args, *filter.EndDate)
		argIdx++
	}

	if filter.TagID != nil {
		baseQuery += ` AND EXISTS (SELECT 1 FROM transaction_tags tt WHERE tt.transaction_id = t.id AND tt.tag_id = $` + strconv.Itoa(argIdx) + `)`
		args = append(args, *filter.TagID)
		argIdx++
	}

	if filter.IsTransfer != nil {
		baseQuery += ` AND t.is_transfer = $` + strconv.Itoa(argIdx)
		args = append(args, *filter.IsTransfer)
		argIdx++
	}

	if filter.Search != "" {
		baseQuery += ` AND t.description ILIKE $` + strconv.Itoa(argIdx)
		args = append(args, "%"+filter.Search+"%")
		argIdx++
	}

	// Uncategorized: transactions with NO tags AND not transfers
	// Matched transfers don't need categorization - they're internal movements
	if filter.Uncategorized {
		baseQuery += ` AND NOT EXISTS (SELECT 1 FROM transaction_tags tt WHERE tt.transaction_id = t.id) AND t.is_transfer = false`
	}

	// NeedsReview: transactions with generic/catch-all tags that haven't been manually reviewed
	if filter.NeedsReview {
		baseQuery += ` AND EXISTS (
			SELECT 1 FROM transaction_tags tt
			JOIN tags tg ON tt.tag_id = tg.id
			WHERE tt.transaction_id = t.id
			AND tg.name IN ('General Merchandise', 'Other Income', 'Other Expense', 'Uncategorized')
		) AND t.reviewed_at IS NULL`
	}

	// Filter by specific tag names
	if len(filter.TagNames) > 0 {
		baseQuery += ` AND EXISTS (
			SELECT 1 FROM transaction_tags tt
			JOIN tags tg ON tt.tag_id = tg.id
			WHERE tt.transaction_id = t.id
			AND tg.name = ANY($` + strconv.Itoa(argIdx) + `)
		)`
		args = append(args, filter.TagNames)
		argIdx++
	}

	// Get total count
	var total int
	err := s.pool.QueryRow(ctx, `SELECT COUNT(*) `+baseQuery, args...).Scan(&total)
	if err != nil {
		return nil, 0, err
	}

	// Get transactions
	query := `SELECT t.id, t.ledger_id, t.date, t.description, t.display_title, t.notes,
		t.teller_transaction_id, t.teller_type, t.teller_category, t.teller_status,
		t.counterparty_name, t.counterparty_type, t.running_balance_cents,
		t.is_transfer, t.transfer_pair_id,
		t.entity_id, t.counterparty_entity_id, t.intermediary_entity_id,
		t.created_at, t.updated_at ` +
		baseQuery + ` ORDER BY t.date DESC, t.created_at DESC`

	if filter.Limit > 0 {
		query += ` LIMIT $` + strconv.Itoa(argIdx)
		args = append(args, filter.Limit)
		argIdx++
	}

	if filter.Offset > 0 {
		query += ` OFFSET $` + strconv.Itoa(argIdx)
		args = append(args, filter.Offset)
	}

	rows, err := s.pool.Query(ctx, query, args...)
	if err != nil {
		return nil, 0, err
	}
	defer rows.Close()

	var transactions []*Transaction
	for rows.Next() {
		t, err := scanBasicTransaction(rows)
		if err != nil {
			return nil, 0, err
		}
		transactions = append(transactions, t)
	}

	return transactions, total, rows.Err()
}

// SumAmounts returns the sum of transaction amounts matching the filter
// Returns inflows (positive) and outflows (negative) separately for display
func (s *TransactionStore) SumAmounts(ctx context.Context, filter TransactionFilter) (inflow, outflow int64, err error) {
	baseQuery := `
		FROM transactions t
		JOIN entries e ON t.id = e.transaction_id
		JOIN accounts a ON e.account_id = a.id
		WHERE t.ledger_id = $1
		AND a.type IN ('asset', 'liability')
	`
	args := []any{filter.LedgerID}
	argIdx := 2

	if filter.AccountID != nil {
		baseQuery += ` AND e.account_id = $` + strconv.Itoa(argIdx)
		args = append(args, *filter.AccountID)
		argIdx++
	}

	if filter.EntityID != nil {
		baseQuery += ` AND t.entity_id = $` + strconv.Itoa(argIdx)
		args = append(args, *filter.EntityID)
		argIdx++
	}

	if filter.StartDate != nil {
		baseQuery += ` AND t.date >= $` + strconv.Itoa(argIdx)
		args = append(args, *filter.StartDate)
		argIdx++
	}

	if filter.EndDate != nil {
		baseQuery += ` AND t.date <= $` + strconv.Itoa(argIdx)
		args = append(args, *filter.EndDate)
		argIdx++
	}

	if filter.TagID != nil {
		baseQuery += ` AND EXISTS (SELECT 1 FROM transaction_tags tt WHERE tt.transaction_id = t.id AND tt.tag_id = $` + strconv.Itoa(argIdx) + `)`
		args = append(args, *filter.TagID)
		argIdx++
	}

	if filter.IsTransfer != nil {
		baseQuery += ` AND t.is_transfer = $` + strconv.Itoa(argIdx)
		args = append(args, *filter.IsTransfer)
		argIdx++
	}

	if filter.Search != "" {
		baseQuery += ` AND t.description ILIKE $` + strconv.Itoa(argIdx)
		args = append(args, "%"+filter.Search+"%")
		argIdx++
	}

	if filter.Uncategorized {
		baseQuery += ` AND NOT EXISTS (SELECT 1 FROM transaction_tags tt WHERE tt.transaction_id = t.id) AND t.is_transfer = false`
	}

	if filter.NeedsReview {
		baseQuery += ` AND EXISTS (
			SELECT 1 FROM transaction_tags tt
			JOIN tags tg ON tt.tag_id = tg.id
			WHERE tt.transaction_id = t.id
			AND tg.name IN ('General Merchandise', 'Other Income', 'Other Expense', 'Uncategorized')
		) AND t.reviewed_at IS NULL`
	}

	if len(filter.TagNames) > 0 {
		baseQuery += ` AND EXISTS (
			SELECT 1 FROM transaction_tags tt
			JOIN tags tg ON tt.tag_id = tg.id
			WHERE tt.transaction_id = t.id
			AND tg.name = ANY($` + strconv.Itoa(argIdx) + `)
		)`
		args = append(args, filter.TagNames)
	}

	// Sum positive and negative amounts separately
	query := `SELECT 
		COALESCE(SUM(CASE WHEN e.amount_cents > 0 THEN e.amount_cents ELSE 0 END), 0) as inflow,
		COALESCE(SUM(CASE WHEN e.amount_cents < 0 THEN e.amount_cents ELSE 0 END), 0) as outflow
	` + baseQuery

	err = s.pool.QueryRow(ctx, query, args...).Scan(&inflow, &outflow)
	return inflow, outflow, err
}

// LoadEntries loads entries for a transaction
func (s *TransactionStore) LoadEntries(ctx context.Context, txn *Transaction) error {
	rows, err := s.pool.Query(ctx, `
		SELECT e.id, e.transaction_id, e.account_id, e.amount_cents, e.currency, e.created_at, a.name, a.type
		FROM entries e
		JOIN accounts a ON e.account_id = a.id
		WHERE e.transaction_id = $1
		ORDER BY e.amount_cents DESC
	`, txn.ID)
	if err != nil {
		return err
	}
	defer rows.Close()

	txn.Entries = nil
	for rows.Next() {
		var e Entry
		if err := rows.Scan(&e.ID, &e.TransactionID, &e.AccountID, &e.AmountCents, &e.Currency, &e.CreatedAt, &e.AccountName, &e.AccountType); err != nil {
			return err
		}
		txn.Entries = append(txn.Entries, &e)
	}

	return rows.Err()
}

// LoadTags loads tags for a transaction
func (s *TransactionStore) LoadTags(ctx context.Context, txn *Transaction) error {
	rows, err := s.pool.Query(ctx, `
		SELECT t.id, t.ledger_id, t.parent_id, t.name, t.color, t.created_at, t.updated_at
		FROM tags t
		JOIN transaction_tags tt ON t.id = tt.tag_id
		WHERE tt.transaction_id = $1
		ORDER BY t.name
	`, txn.ID)
	if err != nil {
		return err
	}
	defer rows.Close()

	txn.Tags = nil
	for rows.Next() {
		var t Tag
		var parentID *uuid.UUID
		if err := rows.Scan(&t.ID, &t.LedgerID, &parentID, &t.Name, &t.Color, &t.CreatedAt, &t.UpdatedAt); err != nil {
			return err
		}
		t.ParentID = parentID
		txn.Tags = append(txn.Tags, &t)
	}

	return rows.Err()
}

// SetTransferPair links two transactions as a transfer pair.
// It marks both transactions as transfers, links them, and recategorizes the contra entries
// to "Internal Transfer" accounts. This ensures:
// 1. Both sides are clearly marked as transfers
// 2. Internal Transfer (Income) + Internal Transfer (Expense) nets to $0
// 3. The real account entries (asset/liability) are NEVER modified
func (s *TransactionStore) SetTransferPair(ctx context.Context, txn1ID, txn2ID uuid.UUID) error {
	return pgx.BeginFunc(ctx, s.pool, func(tx pgx.Tx) error {
		// Mark both transactions as transfers and link them
		_, err := tx.Exec(ctx, `
			UPDATE transactions SET is_transfer = true, transfer_pair_id = $2 WHERE id = $1
		`, txn1ID, txn2ID)
		if err != nil {
			return err
		}

		_, err = tx.Exec(ctx, `
			UPDATE transactions SET is_transfer = true, transfer_pair_id = $2 WHERE id = $1
		`, txn2ID, txn1ID)
		if err != nil {
			return err
		}

		// Get ledger ID from one of the transactions
		var ledgerID uuid.UUID
		err = tx.QueryRow(ctx, `SELECT ledger_id FROM transactions WHERE id = $1`, txn1ID).Scan(&ledgerID)
		if err != nil {
			return err
		}

		// Get or create Internal Transfer suspense account (equity type)
		// Using equity means it won't appear in income/expense reports
		// Both sides of a transfer hit this account and net to zero
		var internalTransferID uuid.UUID

		// Try to find existing Internal Transfer equity account
		err = tx.QueryRow(ctx, `
			SELECT id FROM accounts
			WHERE ledger_id = $1 AND name = 'Internal Transfer' AND type = 'equity'
		`, ledgerID).Scan(&internalTransferID)
		if err != nil {
			// Create it if not found
			err = tx.QueryRow(ctx, `
				INSERT INTO accounts (ledger_id, name, type, is_active, created_at, updated_at)
				VALUES ($1, 'Internal Transfer', 'equity', true, NOW(), NOW())
				RETURNING id
			`, ledgerID).Scan(&internalTransferID)
			if err != nil {
				return err
			}
		}

		// Update contra entries (income/expense type accounts) to Internal Transfer
		// We ONLY touch income/expense entries, NEVER asset/liability entries
		// This preserves the real account balances while properly categorizing transfers
		//
		// All transfer contra entries go to the same equity account.
		// The entries will net to zero (one positive, one negative).
		for _, txnID := range []uuid.UUID{txn1ID, txn2ID} {
			// Find the contra entry (income/expense) to update
			var contraEntryID uuid.UUID
			err = tx.QueryRow(ctx, `
				SELECT e.id
				FROM entries e
				JOIN accounts a ON e.account_id = a.id
				WHERE e.transaction_id = $1 AND a.type IN ('income', 'expense')
			`, txnID).Scan(&contraEntryID)
			if err != nil {
				// No contra entry found, skip
				continue
			}

			_, err = tx.Exec(ctx, `UPDATE entries SET account_id = $2 WHERE id = $1`, contraEntryID, internalTransferID)
			if err != nil {
				return err
			}
		}

		return nil
	})
}

// UnlinkTransferPair unlinks two transactions that were marked as a transfer pair.
// It removes the transfer flags and restores contra entries to Uncategorized Income/Expense.
func (s *TransactionStore) UnlinkTransferPair(ctx context.Context, txnID uuid.UUID) error {
	return pgx.BeginFunc(ctx, s.pool, func(tx pgx.Tx) error {
		// Get the paired transaction and ledger ID
		var pairID *uuid.UUID
		var ledgerID uuid.UUID
		err := tx.QueryRow(ctx, `SELECT transfer_pair_id, ledger_id FROM transactions WHERE id = $1`, txnID).Scan(&pairID, &ledgerID)
		if err != nil || pairID == nil {
			return err
		}

		// Get the Uncategorized Income and Expense accounts
		var uncatIncomeID, uncatExpenseID uuid.UUID
		rows, err := tx.Query(ctx, `
			SELECT id, type FROM accounts
			WHERE ledger_id = $1 AND name IN ('Uncategorized Income', 'Uncategorized Expenses')
		`, ledgerID)
		if err != nil {
			return err
		}
		defer rows.Close()
		for rows.Next() {
			var id uuid.UUID
			var accType AccountType
			if err := rows.Scan(&id, &accType); err != nil {
				return err
			}
			if accType == AccountTypeIncome {
				uncatIncomeID = id
			} else if accType == AccountTypeExpense {
				uncatExpenseID = id
			}
		}
		if err := rows.Err(); err != nil {
			return err
		}

		// Restore contra entries from Internal Transfer back to Uncategorized
		// Use asset entry sign to determine the correct uncategorized account
		for _, tid := range []uuid.UUID{txnID, *pairID} {
			// Find the Internal Transfer entry
			var entryID uuid.UUID
			err = tx.QueryRow(ctx, `
				SELECT e.id
				FROM entries e
				JOIN accounts a ON e.account_id = a.id
				WHERE e.transaction_id = $1 AND a.name = 'Internal Transfer'
			`, tid).Scan(&entryID)
			if err != nil {
				// No Internal Transfer entry found, skip
				continue
			}

			// Find the asset/liability entry to determine money flow direction
			var assetEntryAmount int64
			err = tx.QueryRow(ctx, `
				SELECT e.amount_cents
				FROM entries e
				JOIN accounts a ON e.account_id = a.id
				WHERE e.transaction_id = $1 AND a.type IN ('asset', 'liability')
				LIMIT 1
			`, tid).Scan(&assetEntryAmount)
			if err != nil {
				continue
			}

			// Restore to Uncategorized based on asset entry sign:
			// - Positive (money arriving) → Uncategorized Income
			// - Negative (money leaving) → Uncategorized Expenses
			var targetAccountID uuid.UUID
			if assetEntryAmount > 0 && uncatIncomeID != uuid.Nil {
				targetAccountID = uncatIncomeID
			} else if assetEntryAmount < 0 && uncatExpenseID != uuid.Nil {
				targetAccountID = uncatExpenseID
			}

			if targetAccountID != uuid.Nil {
				_, err = tx.Exec(ctx, `UPDATE entries SET account_id = $2 WHERE id = $1`, entryID, targetAccountID)
				if err != nil {
					return err
				}
			}
		}

		// Unlink both transactions
		_, err = tx.Exec(ctx, `
			UPDATE transactions SET is_transfer = false, transfer_pair_id = NULL WHERE id = $1
		`, txnID)
		if err != nil {
			return err
		}

		_, err = tx.Exec(ctx, `
			UPDATE transactions SET is_transfer = false, transfer_pair_id = NULL WHERE id = $1
		`, *pairID)
		return err
	})
}

// TransferCandidate represents a potential transfer match with entry details
type TransferCandidate struct {
	Transaction *Transaction
	AccountID   uuid.UUID
	AccountName string
	AccountType AccountType
	AmountCents int64
}

// FindTransferCandidates finds potential transfer matches for a transaction
// It looks for transactions with matching amounts (opposite sign) within a date window.
//
// All valid transfers have OPPOSITE signs from the bank's perspective:
// - Asset↔Asset (checking→savings): -$100 leaves checking, +$100 arrives in savings
// - Asset↔Liability (checking→credit card): -$100 leaves checking, +$100 payment on CC
// - Cash advance: +$100 arrives in checking, -$100 charge on CC
func (s *TransactionStore) FindTransferCandidates(ctx context.Context, txn *Transaction, amountCents int64, accountID uuid.UUID, dayWindow int) ([]*TransferCandidate, error) {
	// Find transactions with opposite amount in same ledger within date window
	// that are not already marked as transfers.
	//
	// KEY INSIGHT: If an account has both inflow (+) and outflow (-) of the same amount,
	// these are SEPARATE events (e.g., payroll in, bill payment out), NOT a transfer.
	// A real transfer only touches each account ONCE - money leaves A, arrives at B.
	//
	// So we exclude matches if the original account already has an opposite-amount
	// transaction - that would be the natural "pair" within the same account.
	rows, err := s.pool.Query(ctx, `
		SELECT t.id, t.ledger_id, t.date, t.description, t.notes,
			t.teller_transaction_id, t.teller_type, t.teller_category, t.teller_status,
			t.counterparty_name, t.counterparty_type, t.running_balance_cents,
			t.is_transfer, t.transfer_pair_id, t.created_at, t.updated_at,
			e.account_id, e.amount_cents, a.name as account_name, a.type as account_type
		FROM transactions t
		JOIN entries e ON t.id = e.transaction_id
		JOIN accounts a ON e.account_id = a.id
		WHERE t.ledger_id = $1
			AND t.id != $2
			AND t.is_transfer = false
			AND e.amount_cents = $3
			AND e.account_id != $4
			AND t.date BETWEEN $5 AND $6
			-- Only match entries from asset/liability accounts (not expense/income)
			AND a.type IN ('asset', 'liability')
			-- Exclude candidates that have ANY entry in the original account
			AND NOT EXISTS (
				SELECT 1 FROM entries e2
				WHERE e2.transaction_id = t.id
				AND e2.account_id = $4
			)
			-- KEY FIX: Don't match if the original account has another transaction
			-- with the opposite amount (inflow/outflow pair in same account = not a transfer)
			AND NOT EXISTS (
				SELECT 1 FROM entries e_same
				JOIN transactions t_same ON e_same.transaction_id = t_same.id
				WHERE e_same.account_id = $4
				AND e_same.amount_cents = $3
				AND t_same.id != $2
				AND t_same.is_transfer = false
				AND t_same.date BETWEEN $5 AND $6
			)
		ORDER BY ABS(t.date - $7::date), t.created_at DESC
		LIMIT 10
	`, txn.LedgerID, txn.ID, -amountCents, accountID,
		txn.Date.AddDate(0, 0, -dayWindow), txn.Date.AddDate(0, 0, dayWindow), txn.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var candidates []*TransferCandidate
	for rows.Next() {
		var t Transaction
		var notes, tellerTxnID, tellerType, tellerCategory, tellerStatus sql.NullString
		var counterpartyName, counterpartyType sql.NullString
		var runningBalanceCents sql.NullInt64
		var transferPairID *uuid.UUID
		var c TransferCandidate

		if err := rows.Scan(&t.ID, &t.LedgerID, &t.Date, &t.Description, &notes,
			&tellerTxnID, &tellerType, &tellerCategory, &tellerStatus,
			&counterpartyName, &counterpartyType, &runningBalanceCents,
			&t.IsTransfer, &transferPairID, &t.CreatedAt, &t.UpdatedAt,
			&c.AccountID, &c.AmountCents, &c.AccountName, &c.AccountType); err != nil {
			return nil, err
		}

		applyNullTransactionFields(&t, notes, tellerTxnID, tellerType, tellerCategory, tellerStatus, counterpartyName, counterpartyType, runningBalanceCents)
		t.TransferPairID = transferPairID

		c.Transaction = &t
		candidates = append(candidates, &c)
	}

	return candidates, rows.Err()
}

// GetTransferPair retrieves the paired transaction if this is a transfer
func (s *TransactionStore) GetTransferPair(ctx context.Context, txnID uuid.UUID) (*Transaction, error) {
	var pairID *uuid.UUID
	err := s.pool.QueryRow(ctx, `
		SELECT transfer_pair_id FROM transactions WHERE id = $1
	`, txnID).Scan(&pairID)
	if err != nil || pairID == nil {
		return nil, err
	}
	return s.GetByID(ctx, *pairID)
}

// GetUnmatchedByAccountID returns all transactions for an account that aren't transfers
func (s *TransactionStore) GetUnmatchedByAccountID(ctx context.Context, accountID uuid.UUID) ([]*Transaction, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT DISTINCT t.id, t.ledger_id, t.date, t.description, t.notes,
			t.teller_transaction_id, t.teller_type, t.teller_category, t.teller_status,
			t.counterparty_name, t.counterparty_type, t.running_balance_cents,
			t.is_transfer, t.transfer_pair_id, t.created_at, t.updated_at
		FROM transactions t
		JOIN entries e ON t.id = e.transaction_id
		WHERE e.account_id = $1 AND t.is_transfer = false
		ORDER BY t.date DESC
	`, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var transactions []*Transaction
	for rows.Next() {
		txn := &Transaction{}
		if err := scanCoreTransactionRow(rows, txn); err != nil {
			return nil, err
		}
		transactions = append(transactions, txn)
	}
	return transactions, rows.Err()
}

// GetEntryForAccount returns the entry for a specific transaction and account
func (s *TransactionStore) GetEntryForAccount(ctx context.Context, txnID, accountID uuid.UUID) (*Entry, error) {
	entry := &Entry{}
	err := s.pool.QueryRow(ctx, `
		SELECT id, transaction_id, account_id, amount_cents, currency, created_at
		FROM entries
		WHERE transaction_id = $1 AND account_id = $2
	`, txnID, accountID).Scan(
		&entry.ID, &entry.TransactionID, &entry.AccountID,
		&entry.AmountCents, &entry.Currency, &entry.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	return entry, nil
}

// Categorization status constants
const (
	CategorizationStatusPending    = "pending"
	CategorizationStatusQueued     = "queued"
	CategorizationStatusProcessing = "processing"
	CategorizationStatusDone       = "done"
	CategorizationStatusSkipped    = "skipped"
	CategorizationStatusFailed     = "failed"
)

// Pattern detection status constants
const (
	PatternDetectionStatusPending    = "pending"
	PatternDetectionStatusQueued     = "queued"
	PatternDetectionStatusProcessing = "processing"
	PatternDetectionStatusDone       = "done"
	PatternDetectionStatusSkipped    = "skipped"
	PatternDetectionStatusFailed     = "failed"
)

// Pattern type constants
const (
	PatternTypeSalary            = "salary"
	PatternTypeRecurringBill     = "recurring_bill"
	PatternTypeAccountTransfer   = "account_transfer"
	PatternTypeInvestment        = "investment_contribution"
	PatternTypeHouseholdTransfer = "household_transfer"
	PatternTypeNone              = "none"
)

// Transfer type constants for P2P categorization
const (
	TransferTypeInternal      = "internal"       // Between user's own tracked accounts
	TransferTypeHousehold     = "household"      // To/from spouse, family, shared finances
	TransferTypePersonPayment = "person_payment" // Outbound P2P (Venmo to friend)
	TransferTypePersonReceipt = "person_receipt" // Inbound P2P (friend paid you)
	TransferTypeReimbursement = "reimbursement"  // Friend paying you back
)

// IsP2PTransferType returns true if the transfer type is a person-to-person transfer
func IsP2PTransferType(transferType string) bool {
	switch transferType {
	case TransferTypeHousehold, TransferTypePersonPayment, TransferTypePersonReceipt, TransferTypeReimbursement:
		return true
	}
	return false
}

// GetAllQueuedForCategorization returns transactions from ALL ledgers that need categorization
// Only returns transactions with no tags (uncategorized)
// Also includes transactions stuck in 'processing' status for more than 5 minutes (likely from crashed worker)
func (s *TransactionStore) GetAllQueuedForCategorization(ctx context.Context, limit int, maxRetries int) ([]*Transaction, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT t.id, t.ledger_id, t.date, t.description, t.notes,
			t.teller_transaction_id, t.teller_type, t.teller_category, t.teller_status,
			t.counterparty_name, t.counterparty_type, t.running_balance_cents,
			t.is_transfer, t.transfer_pair_id, t.transfer_type,
			t.categorization_status, t.categorization_error, t.categorization_attempts,
			t.categorization_queued_at, t.categorization_completed_at,
			t.created_at, t.updated_at
		FROM transactions t
		WHERE (
			t.categorization_status IN ('pending', 'queued', 'failed')
			OR (
				t.categorization_status = 'processing'
				AND t.updated_at < NOW() - INTERVAL '5 minutes'
			)
		)
			AND t.is_transfer = false
			AND t.categorization_attempts < $2
			AND NOT EXISTS (SELECT 1 FROM transaction_tags tt WHERE tt.transaction_id = t.id)
		ORDER BY COALESCE(t.categorization_queued_at, t.created_at) ASC
		LIMIT $1
	`, limit, maxRetries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	return s.scanTransactionsWithCategorization(rows)
}

// UpdateCategorizationStatus updates the categorization status of a transaction
func (s *TransactionStore) UpdateCategorizationStatus(ctx context.Context, txnID uuid.UUID, status string, errorMsg string) error {
	now := time.Now()
	var completedAt *time.Time
	if status == CategorizationStatusDone || status == CategorizationStatusSkipped {
		completedAt = &now
	}

	_, err := s.pool.Exec(ctx, `
		UPDATE transactions SET
			categorization_status = $2,
			categorization_error = $3,
			categorization_attempts = categorization_attempts + 1,
			categorization_completed_at = $4,
			updated_at = $5
		WHERE id = $1
	`, txnID, status, NullString(errorMsg), completedAt, now)

	return err
}

// UpdatePatternDetectionStatus updates the pattern detection status of a transaction
func (s *TransactionStore) UpdatePatternDetectionStatus(ctx context.Context, txnID uuid.UUID, status string, errorMsg string) error {
	now := time.Now()

	_, err := s.pool.Exec(ctx, `
		UPDATE transactions SET
			pattern_detection_status = $2,
			pattern_detection_error = $3,
			pattern_detection_attempts = pattern_detection_attempts + 1,
			updated_at = $4
		WHERE id = $1
	`, txnID, status, NullString(errorMsg), now)

	return err
}

// UpdatePatternDetectionResult updates the pattern detection result (type and metadata)
func (s *TransactionStore) UpdatePatternDetectionResult(ctx context.Context, txnID uuid.UUID, patternType string, metadata map[string]interface{}) error {
	now := time.Now()

	var metadataJSON []byte
	var err error
	if metadata != nil {
		metadataJSON, err = json.Marshal(metadata)
		if err != nil {
			return fmt.Errorf("failed to marshal pattern metadata: %w", err)
		}
	}

	_, err = s.pool.Exec(ctx, `
		UPDATE transactions SET
			pattern_type = $2,
			pattern_metadata = $3,
			pattern_detection_status = $4,
			updated_at = $5
		WHERE id = $1
	`, txnID, NullString(patternType), metadataJSON, PatternDetectionStatusDone, now)

	return err
}

// QueueForPatternDetection marks transactions as queued for pattern detection
func (s *TransactionStore) QueueForPatternDetection(ctx context.Context, txnIDs []uuid.UUID) error {
	if len(txnIDs) == 0 {
		return nil
	}

	now := time.Now()
	_, err := s.pool.Exec(ctx, `
		UPDATE transactions SET
			pattern_detection_status = $1,
			updated_at = $2
		WHERE id = ANY($3) AND pattern_detection_status = 'pending'
	`, PatternDetectionStatusQueued, now, txnIDs)

	return err
}

// ExistingPattern holds pattern data that can be inherited by new transactions
type ExistingPattern struct {
	PatternType string
	Frequency   string
	PatternName string
	Confidence  int
}

// GetExistingPatternForEntity finds an existing pattern for an entity
// Returns the most recent, high-confidence pattern that can be inherited
func (s *TransactionStore) GetExistingPatternForEntity(ctx context.Context, entityID uuid.UUID, ledgerID uuid.UUID) (*ExistingPattern, error) {
	var patternType string
	var metadata []byte

	err := s.pool.QueryRow(ctx, `
		SELECT pattern_type, pattern_metadata
		FROM transactions
		WHERE entity_id = $1
			AND ledger_id = $2
			AND pattern_type IS NOT NULL
			AND pattern_type NOT IN ('none', '', 'dismissed')
			AND pattern_detection_status = 'done'
			AND COALESCE((pattern_metadata->>'confidence')::INT, 0) >= 70
		ORDER BY date DESC
		LIMIT 1
	`, entityID, ledgerID).Scan(&patternType, &metadata)

	if err != nil {
		return nil, err
	}

	pattern := &ExistingPattern{
		PatternType: patternType,
	}

	// Extract metadata fields if available
	if len(metadata) > 0 {
		var meta map[string]interface{}
		if err := json.Unmarshal(metadata, &meta); err == nil {
			if freq, ok := meta["frequency"].(string); ok {
				pattern.Frequency = freq
			}
			if name, ok := meta["pattern_name"].(string); ok {
				pattern.PatternName = name
			}
			if conf, ok := meta["confidence"].(float64); ok {
				pattern.Confidence = int(conf)
			}
		}
	}

	return pattern, nil
}

// InheritPattern copies pattern metadata from an existing pattern to a new transaction
// This allows single transactions to immediately become part of established patterns
func (s *TransactionStore) InheritPattern(ctx context.Context, txnID uuid.UUID, pattern *ExistingPattern) error {
	now := time.Now()

	// Build metadata with inherited flag
	metadata := map[string]interface{}{
		"inherited":    true,
		"frequency":    pattern.Frequency,
		"pattern_name": pattern.PatternName,
		"confidence":   pattern.Confidence,
	}

	metadataJSON, err := json.Marshal(metadata)
	if err != nil {
		return fmt.Errorf("failed to marshal inherited pattern metadata: %w", err)
	}

	_, err = s.pool.Exec(ctx, `
		UPDATE transactions SET
			pattern_type = $2,
			pattern_metadata = $3,
			pattern_detection_status = $4,
			updated_at = $5
		WHERE id = $1
	`, txnID, pattern.PatternType, metadataJSON, PatternDetectionStatusDone, now)

	return err
}

// GetQueuedForPatternDetection returns transactions that need pattern detection
func (s *TransactionStore) GetQueuedForPatternDetection(ctx context.Context, ledgerID uuid.UUID, limit int, maxRetries int) ([]*Transaction, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT id, ledger_id, date, description, display_title, notes,
			teller_transaction_id, teller_type, teller_category, teller_status,
			counterparty_name, counterparty_type, running_balance_cents,
			is_transfer, transfer_pair_id, transfer_type,
			categorization_status, categorization_error, categorization_attempts,
			categorization_queued_at, categorization_completed_at,
			recurring_pattern_id, enrichment_status, enrichment_attempts, enrichment_error, enriched_at,
			entity_id, counterparty_entity_id, intermediary_entity_id,
			reviewed_at,
			pattern_type, pattern_metadata, pattern_detection_status, pattern_detection_attempts, pattern_detection_error,
			created_at, updated_at
		FROM transactions
		WHERE ledger_id = $1
			AND pattern_detection_status IN ('pending', 'queued', 'failed')
			AND pattern_detection_attempts < $2
			AND categorization_status = 'done'
		ORDER BY date DESC, created_at DESC
		LIMIT $3
	`, ledgerID, maxRetries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	return s.scanTransactionsWithPatternDetection(rows)
}

// MarkAsProcessing marks transactions as being processed (to prevent concurrent processing)
func (s *TransactionStore) MarkAsProcessing(ctx context.Context, txnIDs []uuid.UUID) error {
	if len(txnIDs) == 0 {
		return nil
	}

	_, err := s.pool.Exec(ctx, `
		UPDATE transactions SET
			categorization_status = $1,
			updated_at = $2
		WHERE id = ANY($3)
	`, CategorizationStatusProcessing, time.Now(), txnIDs)

	return err
}

// GetCategorizationQueueStats returns stats about the categorization queue
type CategorizationQueueStats struct {
	Pending    int `json:"pending"`
	Queued     int `json:"queued"`
	Processing int `json:"processing"`
	Done       int `json:"done"`
	Skipped    int `json:"skipped"`
	Failed     int `json:"failed"`
}

func (s *TransactionStore) GetCategorizationQueueStats(ctx context.Context, ledgerID uuid.UUID) (*CategorizationQueueStats, error) {
	stats := &CategorizationQueueStats{}

	rows, err := s.pool.Query(ctx, `
		SELECT categorization_status, COUNT(*) 
		FROM transactions 
		WHERE ledger_id = $1 
		GROUP BY categorization_status
	`, ledgerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	for rows.Next() {
		var status string
		var count int
		if err := rows.Scan(&status, &count); err != nil {
			return nil, err
		}
		switch status {
		case CategorizationStatusPending:
			stats.Pending = count
		case CategorizationStatusQueued:
			stats.Queued = count
		case CategorizationStatusProcessing:
			stats.Processing = count
		case CategorizationStatusDone:
			stats.Done = count
		case CategorizationStatusSkipped:
			stats.Skipped = count
		case CategorizationStatusFailed:
			stats.Failed = count
		}
	}

	return stats, rows.Err()
}

// Helper to scan transactions with categorization fields
func (s *TransactionStore) scanTransactionsWithCategorization(rows pgx.Rows) ([]*Transaction, error) {
	var transactions []*Transaction
	for rows.Next() {
		var t Transaction
		var notes, tellerTxnID, tellerType, tellerCategory, tellerStatus sql.NullString
		var counterpartyName, counterpartyType sql.NullString
		var runningBalanceCents sql.NullInt64
		var transferPairID *uuid.UUID
		var transferType sql.NullString
		var catStatus, catError sql.NullString
		var catAttempts sql.NullInt64
		var catQueuedAt, catCompletedAt sql.NullTime

		if err := rows.Scan(&t.ID, &t.LedgerID, &t.Date, &t.Description, &notes,
			&tellerTxnID, &tellerType, &tellerCategory, &tellerStatus,
			&counterpartyName, &counterpartyType, &runningBalanceCents,
			&t.IsTransfer, &transferPairID, &transferType,
			&catStatus, &catError, &catAttempts,
			&catQueuedAt, &catCompletedAt,
			&t.CreatedAt, &t.UpdatedAt); err != nil {
			return nil, err
		}

		applyNullTransactionFields(&t, notes, tellerTxnID, tellerType, tellerCategory, tellerStatus, counterpartyName, counterpartyType, runningBalanceCents)
		t.TransferPairID = transferPairID
		t.TransferType = transferType.String
		t.CategorizationStatus = catStatus.String
		t.CategorizationError = catError.String
		t.CategorizationAttempts = int(catAttempts.Int64)
		t.CategorizationQueuedAt = nullTimePtr(catQueuedAt)
		t.CategorizationCompletedAt = nullTimePtr(catCompletedAt)

		transactions = append(transactions, &t)
	}

	return transactions, rows.Err()
}

// Helper to scan transactions with pattern detection fields
func (s *TransactionStore) scanTransactionsWithPatternDetection(rows pgx.Rows) ([]*Transaction, error) {
	var transactions []*Transaction
	for rows.Next() {
		var t Transaction
		var notes, displayTitle sql.NullString
		var tellerTxnID, tellerType, tellerCategory, tellerStatus sql.NullString
		var counterpartyName, counterpartyType sql.NullString
		var runningBalanceCents sql.NullInt64
		var transferPairID *uuid.UUID
		var transferType sql.NullString
		var catStatus, catError sql.NullString
		var catAttempts sql.NullInt64
		var catQueuedAt, catCompletedAt sql.NullTime
		var recurringPatternID *uuid.UUID
		var enrichmentStatus, enrichmentError sql.NullString
		var enrichmentAttempts sql.NullInt64
		var enrichedAt sql.NullTime
		var entityID, counterpartyEntityID, intermediaryEntityID *uuid.UUID
		var reviewedAt sql.NullTime
		var patternType, patternStatus, patternError sql.NullString
		var patternMetadata []byte
		var patternAttempts sql.NullInt64

		if err := rows.Scan(&t.ID, &t.LedgerID, &t.Date, &t.Description, &displayTitle, &notes,
			&tellerTxnID, &tellerType, &tellerCategory, &tellerStatus,
			&counterpartyName, &counterpartyType, &runningBalanceCents,
			&t.IsTransfer, &transferPairID, &transferType,
			&catStatus, &catError, &catAttempts,
			&catQueuedAt, &catCompletedAt,
			&recurringPatternID, &enrichmentStatus, &enrichmentAttempts, &enrichmentError, &enrichedAt,
			&entityID, &counterpartyEntityID, &intermediaryEntityID,
			&reviewedAt,
			&patternType, &patternMetadata, &patternStatus, &patternAttempts, &patternError,
			&t.CreatedAt, &t.UpdatedAt); err != nil {
			return nil, err
		}

		t.DisplayTitle = displayTitle.String
		applyNullTransactionFields(&t, notes, tellerTxnID, tellerType, tellerCategory, tellerStatus, counterpartyName, counterpartyType, runningBalanceCents)
		t.TransferPairID = transferPairID
		t.TransferType = transferType.String
		t.CategorizationStatus = catStatus.String
		t.CategorizationError = catError.String
		t.CategorizationAttempts = int(catAttempts.Int64)
		t.CategorizationQueuedAt = nullTimePtr(catQueuedAt)
		t.CategorizationCompletedAt = nullTimePtr(catCompletedAt)
		t.RecurringPatternID = recurringPatternID
		t.EnrichmentStatus = enrichmentStatus.String
		t.EnrichmentAttempts = int(enrichmentAttempts.Int64)
		t.EnrichmentError = enrichmentError.String
		t.EnrichedAt = nullTimePtr(enrichedAt)
		t.EntityID = entityID
		t.CounterpartyEntityID = counterpartyEntityID
		t.IntermediaryEntityID = intermediaryEntityID
		t.ReviewedAt = nullTimePtr(reviewedAt)
		t.PatternType = patternType.String
		t.PatternDetectionStatus = patternStatus.String
		t.PatternDetectionAttempts = int(patternAttempts.Int64)
		t.PatternDetectionError = patternError.String
		if len(patternMetadata) > 0 {
			if err := json.Unmarshal(patternMetadata, &t.PatternMetadata); err != nil {
				// Log error but don't fail - metadata is optional
				slog.Error("failed to unmarshal pattern metadata for transaction", "id", t.ID, "err", err)
			}
		}

		transactions = append(transactions, &t)
	}

	return transactions, rows.Err()
}

// resetCategorizationByIDs resets categorization status to queued and removes tags for the given IDs.
func (s *TransactionStore) resetCategorizationByIDs(ctx context.Context, txnIDs []uuid.UUID) error {
	now := time.Now()
	result, err := s.pool.Exec(ctx, `
		UPDATE transactions SET
			categorization_status = $1,
			categorization_error = NULL,
			categorization_attempts = 0,
			categorization_queued_at = $2,
			categorization_completed_at = NULL,
			updated_at = $2
		WHERE id = ANY($3)
	`, CategorizationStatusQueued, now, txnIDs)
	if err != nil {
		return err
	}
	slog.InfoContext(ctx, "reset transactions for reprocessing", "count", result.RowsAffected())

	tagResult, err := s.pool.Exec(ctx, `
		DELETE FROM transaction_tags WHERE transaction_id = ANY($1)
	`, txnIDs)
	if err != nil {
		return err
	}
	slog.InfoContext(ctx, "deleted transaction tags", "count", tagResult.RowsAffected())
	return nil
}

// MarkForRecategorization resets transactions to pending status so they get reprocessed.
// Also removes their existing tags so they can be re-categorized fresh.
func (s *TransactionStore) MarkForRecategorization(ctx context.Context, txnIDs []uuid.UUID) error {
	if len(txnIDs) == 0 {
		return nil
	}
	return s.resetCategorizationByIDs(ctx, txnIDs)
}

// MarkAllForRecategorization resets ALL transactions in a ledger for reprocessing
func (s *TransactionStore) MarkAllForRecategorization(ctx context.Context, ledgerID uuid.UUID) (int, error) {
	now := time.Now()

	// Reset categorization status for all non-transfer transactions
	result, err := s.pool.Exec(ctx, `
		UPDATE transactions SET
			categorization_status = $1,
			categorization_error = NULL,
			categorization_attempts = 0,
			categorization_queued_at = $2,
			categorization_completed_at = NULL,
			updated_at = $2
		WHERE ledger_id = $3 AND is_transfer = false
	`, CategorizationStatusQueued, now, ledgerID)
	if err != nil {
		return 0, err
	}

	count := int(result.RowsAffected())

	// Remove existing tags from all transactions in this ledger
	_, err = s.pool.Exec(ctx, `
		DELETE FROM transaction_tags 
		WHERE transaction_id IN (
			SELECT id FROM transactions WHERE ledger_id = $1 AND is_transfer = false
		)
	`, ledgerID)

	return count, err
}

// MarkForRecategorizationByTagName finds all transactions with the given tag name and marks them for recategorization.
// Returns the number of transactions affected.
func (s *TransactionStore) MarkForRecategorizationByTagName(ctx context.Context, ledgerID uuid.UUID, tagName string) (int, error) {
	var tagID uuid.UUID
	err := s.pool.QueryRow(ctx, `
		SELECT id FROM tags
		WHERE ledger_id = $1 AND LOWER(name) = LOWER($2)
	`, ledgerID, tagName).Scan(&tagID)
	if err != nil {
		return 0, err
	}

	rows, err := s.pool.Query(ctx, `
		SELECT transaction_id FROM transaction_tags WHERE tag_id = $1
	`, tagID)
	if err != nil {
		return 0, err
	}
	defer rows.Close()

	var txnIDs []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return 0, err
		}
		txnIDs = append(txnIDs, id)
	}
	if err := rows.Err(); err != nil {
		return 0, err
	}

	if len(txnIDs) == 0 {
		return 0, nil
	}

	if err := s.resetCategorizationByIDs(ctx, txnIDs); err != nil {
		return 0, err
	}
	return len(txnIDs), nil
}

// MarkAllForRecategorizationByTagName finds all transactions across ALL ledgers with the given tag name
// and marks them for recategorization. Returns the number of transactions affected.
func (s *TransactionStore) MarkAllForRecategorizationByTagName(ctx context.Context, tagName string) (int, error) {
	now := time.Now()

	// Find all tag IDs with this name (case-insensitive) across all ledgers
	rows, err := s.pool.Query(ctx, `
		SELECT id FROM tags WHERE LOWER(name) = LOWER($1)
	`, tagName)
	if err != nil {
		return 0, err
	}
	defer rows.Close()

	var tagIDs []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return 0, err
		}
		tagIDs = append(tagIDs, id)
	}
	if err := rows.Err(); err != nil {
		return 0, err
	}

	if len(tagIDs) == 0 {
		return 0, nil
	}

	// Get all transaction IDs with any of these tags
	txnRows, err := s.pool.Query(ctx, `
		SELECT DISTINCT transaction_id FROM transaction_tags WHERE tag_id = ANY($1)
	`, tagIDs)
	if err != nil {
		return 0, err
	}
	defer txnRows.Close()

	var txnIDs []uuid.UUID
	for txnRows.Next() {
		var id uuid.UUID
		if err := txnRows.Scan(&id); err != nil {
			return 0, err
		}
		txnIDs = append(txnIDs, id)
	}
	if err := txnRows.Err(); err != nil {
		return 0, err
	}

	if len(txnIDs) == 0 {
		return 0, nil
	}

	// Reset categorization and P2P transfer type status
	// This puts them back in the categorization queue which will detect P2P transfers
	_, err = s.pool.Exec(ctx, `
		UPDATE transactions SET
			transfer_type = NULL,
			categorization_status = $1,
			categorization_error = NULL,
			categorization_attempts = 0,
			categorization_queued_at = $2,
			categorization_completed_at = NULL,
			updated_at = $2
		WHERE id = ANY($3)
	`, CategorizationStatusQueued, now, txnIDs)
	if err != nil {
		return 0, err
	}

	// Remove existing tags from these transactions
	_, err = s.pool.Exec(ctx, `
		DELETE FROM transaction_tags WHERE transaction_id = ANY($1)
	`, txnIDs)
	if err != nil {
		return 0, err
	}

	return len(txnIDs), nil
}

// SearchByDescription finds transactions matching a search term (for re-categorization)
func (s *TransactionStore) SearchByDescription(ctx context.Context, ledgerID uuid.UUID, search string) ([]*Transaction, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT id, ledger_id, date, description, notes,
			teller_transaction_id, teller_type, teller_category, teller_status,
			counterparty_name, counterparty_type, running_balance_cents,
			is_transfer, transfer_pair_id, created_at, updated_at
		FROM transactions
		WHERE ledger_id = $1 AND description ILIKE $2
		ORDER BY date DESC
	`, ledgerID, "%"+search+"%")
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var transactions []*Transaction
	for rows.Next() {
		var t Transaction
		if err := scanCoreTransactionRow(rows, &t); err != nil {
			return nil, err
		}
		transactions = append(transactions, &t)
	}

	return transactions, rows.Err()
}

// Note: EnrichmentStatus constants are defined in entity.go

// QueueForEnrichment queues transactions for the unified processing worker.
// Note: enrichment_status is no longer used - only categorization_status matters.
func (s *TransactionStore) QueueForEnrichment(ctx context.Context, txnIDs []uuid.UUID) error {
	if len(txnIDs) == 0 {
		return nil
	}

	now := time.Now()
	_, err := s.pool.Exec(ctx, `
		UPDATE transactions SET
			categorization_status = $1,
			categorization_queued_at = $2,
			updated_at = $3
		WHERE id = ANY($4)
	`, CategorizationStatusPending, now, now, txnIDs)

	return err
}

// UpdateEnrichment updates entity-related fields on a transaction.
// Note: enrichment_status is no longer used by the unified processing worker.
func (s *TransactionStore) UpdateEnrichment(ctx context.Context, txn *Transaction) error {
	now := time.Now()
	_, err := s.pool.Exec(ctx, `
		UPDATE transactions SET
			recurring_pattern_id = $2,
			enriched_at = $3,
			entity_id = $4,
			counterparty_entity_id = $5,
			intermediary_entity_id = $6,
			updated_at = $7
		WHERE id = $1
	`, txn.ID, txn.RecurringPatternID,
		txn.EnrichedAt,
		txn.EntityID, txn.CounterpartyEntityID, txn.IntermediaryEntityID, now)

	return err
}

// SetDisplayTitle updates the display title for a transaction
func (s *TransactionStore) SetDisplayTitle(ctx context.Context, txnID uuid.UUID, title string) error {
	_, err := s.pool.Exec(ctx, `
		UPDATE transactions SET
			display_title = $2,
			updated_at = $3
		WHERE id = $1
	`, txnID, NullString(title), time.Now())

	return err
}

// SetEnrichmentStatus updates just the enrichment status
// SetEnrichmentStatus updates the enrichment status (simple version for done/skipped)
func (s *TransactionStore) SetEnrichmentStatus(ctx context.Context, txnID uuid.UUID, status string) error {
	var enrichedAt *time.Time
	now := time.Now()
	if status == EnrichmentStatusDone {
		enrichedAt = &now
	}

	_, err := s.pool.Exec(ctx, `
		UPDATE transactions SET
			enrichment_status = $2,
			enriched_at = $3,
			enrichment_attempts = COALESCE(enrichment_attempts, 0) + 1,
			updated_at = $4
		WHERE id = $1
	`, txnID, status, enrichedAt, now)

	return err
}

func (s *TransactionStore) loadEntity(ctx context.Context, idPtr *uuid.UUID, setter func(*Entity), entityStore *EntityStore) error {
	if idPtr == nil {
		return nil
	}
	entity, err := entityStore.GetByID(ctx, *idPtr)
	if err != nil {
		return err
	}
	setter(entity)
	return nil
}

// LoadEntity loads the entity for a transaction
func (s *TransactionStore) LoadEntity(ctx context.Context, txn *Transaction, entityStore *EntityStore) error {
	return s.loadEntity(ctx, txn.EntityID, func(e *Entity) { txn.Entity = e }, entityStore)
}

// LoadAllEntities loads all entity references for a transaction
func (s *TransactionStore) LoadAllEntities(ctx context.Context, txn *Transaction, entityStore *EntityStore) error {
	if err := s.loadEntity(ctx, txn.EntityID, func(e *Entity) { txn.Entity = e }, entityStore); err != nil {
		return err
	}
	if err := s.loadEntity(ctx, txn.CounterpartyEntityID, func(e *Entity) { txn.CounterpartyEntity = e }, entityStore); err != nil {
		return err
	}
	return s.loadEntity(ctx, txn.IntermediaryEntityID, func(e *Entity) { txn.IntermediaryEntity = e }, entityStore)
}

func (s *TransactionStore) setEntityFieldID(ctx context.Context, txnID, entityID uuid.UUID, column string) error {
	_, err := s.pool.Exec(ctx,
		"UPDATE transactions SET "+column+" = $2, updated_at = $3 WHERE id = $1",
		txnID, entityID, time.Now())
	return err
}

// SetEntityID sets the entity ID for a transaction
func (s *TransactionStore) SetEntityID(ctx context.Context, txnID, entityID uuid.UUID) error {
	return s.setEntityFieldID(ctx, txnID, entityID, "entity_id")
}

// SetCounterpartyEntityID sets the counterparty entity ID for a transaction
func (s *TransactionStore) SetCounterpartyEntityID(ctx context.Context, txnID, entityID uuid.UUID) error {
	return s.setEntityFieldID(ctx, txnID, entityID, "counterparty_entity_id")
}

// SetIntermediaryEntityID sets the intermediary entity ID for a transaction
func (s *TransactionStore) SetIntermediaryEntityID(ctx context.Context, txnID, entityID uuid.UUID) error {
	return s.setEntityFieldID(ctx, txnID, entityID, "intermediary_entity_id")
}

// AddTag adds a tag to a transaction (used by fast-path enrichment)
func (s *TransactionStore) AddTag(ctx context.Context, transactionID, tagID uuid.UUID) error {
	_, err := s.pool.Exec(ctx, `
		INSERT INTO transaction_tags (transaction_id, tag_id, created_at)
		VALUES ($1, $2, $3)
		ON CONFLICT DO NOTHING
	`, transactionID, tagID, time.Now())
	return err
}

// SetTransferType updates the transfer_type for a transaction
func (s *TransactionStore) SetTransferType(ctx context.Context, txnID uuid.UUID, transferType string) error {
	_, err := s.pool.Exec(ctx, `
		UPDATE transactions SET
			transfer_type = $2,
			updated_at = $3
		WHERE id = $1
	`, txnID, NullString(transferType), time.Now())
	return err
}

// GetP2PTransactionsByCounterparty returns recent P2P transactions to/from the same counterparty
// Used for pattern detection (frequent transfers to same person = likely household)
func (s *TransactionStore) GetP2PTransactionsByCounterparty(ctx context.Context, ledgerID uuid.UUID, counterpartyName string, limit int) ([]*Transaction, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT id, ledger_id, date, description, counterparty_name, counterparty_type, transfer_type
		FROM transactions
		WHERE ledger_id = $1 
			AND LOWER(counterparty_name) = LOWER($2)
			AND transfer_type IS NOT NULL
		ORDER BY date DESC
		LIMIT $3
	`, ledgerID, counterpartyName, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var transactions []*Transaction
	for rows.Next() {
		var t Transaction
		var cpName, cpType, tType sql.NullString

		if err := rows.Scan(&t.ID, &t.LedgerID, &t.Date, &t.Description,
			&cpName, &cpType, &tType); err != nil {
			return nil, err
		}

		t.CounterpartyName = cpName.String
		t.CounterpartyType = cpType.String
		t.TransferType = tType.String
		transactions = append(transactions, &t)
	}

	return transactions, rows.Err()
}

// ExistsByDateDescriptionAmount checks if a transaction already exists with the same
// date, description, and amount for a specific account. This helps detect duplicates
// when Teller assigns new transaction IDs after an enrollment reconnection.
func (s *TransactionStore) ExistsByDateDescriptionAmount(ctx context.Context, accountID uuid.UUID, date time.Time, description string, amountCents int64) (bool, error) {
	var exists bool
	err := s.pool.QueryRow(ctx, `
		SELECT EXISTS (
			SELECT 1 FROM transactions t
			JOIN entries e ON t.id = e.transaction_id
			WHERE e.account_id = $1
			  AND t.date = $2
			  AND t.description = $3
			  AND e.amount_cents = $4
		)
	`, accountID, date, description, amountCents).Scan(&exists)
	return exists, err
}

// BulkMarkAsReviewed marks multiple transactions as reviewed by setting reviewed_at
// This removes them from the "needs review" filter without changing their tags
func (s *TransactionStore) BulkMarkAsReviewed(ctx context.Context, ids []uuid.UUID) (int64, error) {
	if len(ids) == 0 {
		return 0, nil
	}

	result, err := s.pool.Exec(ctx, `
		UPDATE transactions 
		SET reviewed_at = NOW(), updated_at = NOW()
		WHERE id = ANY($1)
	`, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

// UpdateEmbedding updates the embedding for a transaction
func (s *TransactionStore) UpdateEmbedding(ctx context.Context, txnID uuid.UUID, embedding []float32, model string) error {
	now := time.Now()
	_, err := s.pool.Exec(ctx, `
		UPDATE transactions SET
			embedding = $2,
			embedding_model = $3,
			embedding_updated_at = $4,
			updated_at = $5
		WHERE id = $1
	`, txnID, embedding, model, now, now)
	return err
}

// GetTransactionsWithoutEmbedding returns transactions that don't have an embedding yet
func (s *TransactionStore) GetTransactionsWithoutEmbedding(ctx context.Context, ledgerID uuid.UUID, limit int) ([]*Transaction, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT id, ledger_id, date, description, display_title, 
			entity_id, pattern_type, categorization_status
		FROM transactions 
		WHERE ledger_id = $1
			AND embedding IS NULL
			AND categorization_status = 'done'
		ORDER BY date DESC
		LIMIT $2
	`, ledgerID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var transactions []*Transaction
	for rows.Next() {
		var t Transaction
		var displayTitle, patternType sql.NullString
		var entityID *uuid.UUID
		if err := rows.Scan(&t.ID, &t.LedgerID, &t.Date, &t.Description, &displayTitle,
			&entityID, &patternType, &t.CategorizationStatus); err != nil {
			return nil, err
		}
		t.DisplayTitle = displayTitle.String
		t.PatternType = patternType.String
		t.EntityID = entityID
		transactions = append(transactions, &t)
	}

	return transactions, rows.Err()
}

// CountTransactionsWithEmbedding returns counts of transactions with/without embeddings
func (s *TransactionStore) CountTransactionsWithEmbedding(ctx context.Context, ledgerID uuid.UUID) (withEmbedding, withoutEmbedding int, err error) {
	err = s.pool.QueryRow(ctx, `
		SELECT 
			COUNT(*) FILTER (WHERE embedding IS NOT NULL) as with_embedding,
			COUNT(*) FILTER (WHERE embedding IS NULL) as without_embedding
		FROM transactions
		WHERE ledger_id = $1
	`, ledgerID).Scan(&withEmbedding, &withoutEmbedding)
	return
}

// TransactionSimilarityResult represents a similarity search result
type TransactionSimilarityResult struct {
	Transaction *Transaction
	Similarity  float32
}

// SpendingSummaryGroup represents aggregated spending for a category/entity/account
type SpendingSummaryGroup struct {
	GroupName        string `json:"name"`
	TotalCents       int64  `json:"total_cents"`
	TransactionCount int    `json:"transaction_count"`
}

// GetSpendingSummary returns aggregated spending using efficient SQL GROUP BY.
// This is much faster than loading individual transactions - single query vs N+1.
// groupBy can be "tag", "entity", or "account"
func (s *TransactionStore) GetSpendingSummary(ctx context.Context, ledgerID uuid.UUID, startDate, endDate time.Time, groupBy string) ([]SpendingSummaryGroup, int64, error) {
	var query string

	switch groupBy {
	case "entity":
		query = `
			SELECT COALESCE(ent.name, COALESCE(t.display_title, 'Unknown')) as group_name,
				   ABS(SUM(e.amount_cents)) as total_cents,
				   COUNT(DISTINCT t.id) as transaction_count
			FROM transactions t
			JOIN entries e ON e.transaction_id = t.id
			JOIN accounts a ON e.account_id = a.id
			LEFT JOIN entities ent ON t.entity_id = ent.id
			WHERE t.ledger_id = $1
			  AND t.date >= $2
			  AND t.date <= $3
			  AND t.is_transfer = false
			  AND a.type IN ('asset', 'liability')
			  AND e.amount_cents < 0
			GROUP BY COALESCE(ent.name, COALESCE(t.display_title, 'Unknown'))
			ORDER BY total_cents DESC
		`
	case "account":
		query = `
			SELECT a.name as group_name,
				   ABS(SUM(e.amount_cents)) as total_cents,
				   COUNT(DISTINCT t.id) as transaction_count
			FROM transactions t
			JOIN entries e ON e.transaction_id = t.id
			JOIN accounts a ON e.account_id = a.id
			WHERE t.ledger_id = $1
			  AND t.date >= $2
			  AND t.date <= $3
			  AND t.is_transfer = false
			  AND a.type IN ('asset', 'liability')
			  AND e.amount_cents < 0
			GROUP BY a.name
			ORDER BY total_cents DESC
		`
	default: // "tag" is default
		query = `
			SELECT COALESCE(tg.name, 'Uncategorized') as group_name,
				   ABS(SUM(e.amount_cents)) as total_cents,
				   COUNT(DISTINCT t.id) as transaction_count
			FROM transactions t
			JOIN entries e ON e.transaction_id = t.id
			JOIN accounts a ON e.account_id = a.id
			LEFT JOIN transaction_tags tt ON tt.transaction_id = t.id
			LEFT JOIN tags tg ON tg.id = tt.tag_id
			WHERE t.ledger_id = $1
			  AND t.date >= $2
			  AND t.date <= $3
			  AND t.is_transfer = false
			  AND a.type IN ('asset', 'liability')
			  AND e.amount_cents < 0
			GROUP BY tg.name
			ORDER BY total_cents DESC
		`
	}

	rows, err := s.pool.Query(ctx, query, ledgerID, startDate, endDate)
	if err != nil {
		return nil, 0, fmt.Errorf("spending summary query failed: %w", err)
	}
	defer rows.Close()

	var groups []SpendingSummaryGroup
	var totalSpending int64

	for rows.Next() {
		var g SpendingSummaryGroup
		if err := rows.Scan(&g.GroupName, &g.TotalCents, &g.TransactionCount); err != nil {
			return nil, 0, err
		}
		totalSpending += g.TotalCents
		groups = append(groups, g)
	}

	if err := rows.Err(); err != nil {
		return nil, 0, err
	}

	return groups, totalSpending, nil
}

// FindSimilarTransactions finds transactions similar to the given embedding
func (s *TransactionStore) FindSimilarTransactions(ctx context.Context, embedding []float32, ledgerID uuid.UUID, limit int, minSimilarity float32) ([]*TransactionSimilarityResult, error) {
	if len(embedding) == 0 {
		return nil, fmt.Errorf("embedding cannot be empty")
	}

	rows, err := s.pool.Query(ctx, `
		SELECT t.id, t.ledger_id, t.date, t.description, t.display_title,
			t.entity_id, t.pattern_type, t.categorization_status,
			cosine_similarity(t.embedding, $1) as similarity
		FROM transactions t
		WHERE t.ledger_id = $2
			AND t.embedding IS NOT NULL
			AND cosine_similarity(t.embedding, $1) >= $3
		ORDER BY similarity DESC
		LIMIT $4
	`, embedding, ledgerID, minSimilarity, limit)
	if err != nil {
		return nil, fmt.Errorf("similarity search failed: %w", err)
	}
	defer rows.Close()

	var results []*TransactionSimilarityResult
	for rows.Next() {
		var t Transaction
		var displayTitle, patternType sql.NullString
		var entityID *uuid.UUID
		var similarity float32

		if err := rows.Scan(&t.ID, &t.LedgerID, &t.Date, &t.Description, &displayTitle,
			&entityID, &patternType, &t.CategorizationStatus, &similarity); err != nil {
			return nil, err
		}
		t.DisplayTitle = displayTitle.String
		t.PatternType = patternType.String
		t.EntityID = entityID

		results = append(results, &TransactionSimilarityResult{
			Transaction: &t,
			Similarity:  similarity,
		})
	}

	return results, rows.Err()
}
